// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: hello.proto

#include "hello.pb.h"
#include "hello.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace protocol {
namespace hello {
namespace v1 {

static const char* HelloAPI_method_names[] = {
  "/protocol.hello.v1.HelloAPI/sayHello",
};

std::unique_ptr< HelloAPI::Stub> HelloAPI::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< HelloAPI::Stub> stub(new HelloAPI::Stub(channel));
  return stub;
}

HelloAPI::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_sayHello_(HelloAPI_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status HelloAPI::Stub::sayHello(::grpc::ClientContext* context, const ::protocol::hello::v1::HelloReq& request, ::protocol::hello::v1::HelloResp* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_sayHello_, context, request, response);
}

void HelloAPI::Stub::experimental_async::sayHello(::grpc::ClientContext* context, const ::protocol::hello::v1::HelloReq* request, ::protocol::hello::v1::HelloResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_sayHello_, context, request, response, std::move(f));
}

void HelloAPI::Stub::experimental_async::sayHello(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::protocol::hello::v1::HelloResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_sayHello_, context, request, response, std::move(f));
}

void HelloAPI::Stub::experimental_async::sayHello(::grpc::ClientContext* context, const ::protocol::hello::v1::HelloReq* request, ::protocol::hello::v1::HelloResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_sayHello_, context, request, response, reactor);
}

void HelloAPI::Stub::experimental_async::sayHello(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::protocol::hello::v1::HelloResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_sayHello_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::protocol::hello::v1::HelloResp>* HelloAPI::Stub::AsyncsayHelloRaw(::grpc::ClientContext* context, const ::protocol::hello::v1::HelloReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::protocol::hello::v1::HelloResp>::Create(channel_.get(), cq, rpcmethod_sayHello_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::protocol::hello::v1::HelloResp>* HelloAPI::Stub::PrepareAsyncsayHelloRaw(::grpc::ClientContext* context, const ::protocol::hello::v1::HelloReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::protocol::hello::v1::HelloResp>::Create(channel_.get(), cq, rpcmethod_sayHello_, context, request, false);
}

HelloAPI::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HelloAPI_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HelloAPI::Service, ::protocol::hello::v1::HelloReq, ::protocol::hello::v1::HelloResp>(
          [](HelloAPI::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::protocol::hello::v1::HelloReq* req,
             ::protocol::hello::v1::HelloResp* resp) {
               return service->sayHello(ctx, req, resp);
             }, this)));
}

HelloAPI::Service::~Service() {
}

::grpc::Status HelloAPI::Service::sayHello(::grpc::ServerContext* context, const ::protocol::hello::v1::HelloReq* request, ::protocol::hello::v1::HelloResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace protocol
}  // namespace hello
}  // namespace v1

