// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: hello.proto
#ifndef GRPC_hello_2eproto__INCLUDED
#define GRPC_hello_2eproto__INCLUDED

#include "hello.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace protocol {
namespace hello {
namespace v1 {

// Hello API
class HelloAPI final {
 public:
  static constexpr char const* service_full_name() {
    return "protocol.hello.v1.HelloAPI";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status sayHello(::grpc::ClientContext* context, const ::protocol::hello::v1::HelloReq& request, ::protocol::hello::v1::HelloResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::protocol::hello::v1::HelloResp>> AsyncsayHello(::grpc::ClientContext* context, const ::protocol::hello::v1::HelloReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::protocol::hello::v1::HelloResp>>(AsyncsayHelloRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::protocol::hello::v1::HelloResp>> PrepareAsyncsayHello(::grpc::ClientContext* context, const ::protocol::hello::v1::HelloReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::protocol::hello::v1::HelloResp>>(PrepareAsyncsayHelloRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void sayHello(::grpc::ClientContext* context, const ::protocol::hello::v1::HelloReq* request, ::protocol::hello::v1::HelloResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void sayHello(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::protocol::hello::v1::HelloResp* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void sayHello(::grpc::ClientContext* context, const ::protocol::hello::v1::HelloReq* request, ::protocol::hello::v1::HelloResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void sayHello(::grpc::ClientContext* context, const ::protocol::hello::v1::HelloReq* request, ::protocol::hello::v1::HelloResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void sayHello(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::protocol::hello::v1::HelloResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void sayHello(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::protocol::hello::v1::HelloResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::protocol::hello::v1::HelloResp>* AsyncsayHelloRaw(::grpc::ClientContext* context, const ::protocol::hello::v1::HelloReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::protocol::hello::v1::HelloResp>* PrepareAsyncsayHelloRaw(::grpc::ClientContext* context, const ::protocol::hello::v1::HelloReq& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status sayHello(::grpc::ClientContext* context, const ::protocol::hello::v1::HelloReq& request, ::protocol::hello::v1::HelloResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::protocol::hello::v1::HelloResp>> AsyncsayHello(::grpc::ClientContext* context, const ::protocol::hello::v1::HelloReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::protocol::hello::v1::HelloResp>>(AsyncsayHelloRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::protocol::hello::v1::HelloResp>> PrepareAsyncsayHello(::grpc::ClientContext* context, const ::protocol::hello::v1::HelloReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::protocol::hello::v1::HelloResp>>(PrepareAsyncsayHelloRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void sayHello(::grpc::ClientContext* context, const ::protocol::hello::v1::HelloReq* request, ::protocol::hello::v1::HelloResp* response, std::function<void(::grpc::Status)>) override;
      void sayHello(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::protocol::hello::v1::HelloResp* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void sayHello(::grpc::ClientContext* context, const ::protocol::hello::v1::HelloReq* request, ::protocol::hello::v1::HelloResp* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void sayHello(::grpc::ClientContext* context, const ::protocol::hello::v1::HelloReq* request, ::protocol::hello::v1::HelloResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void sayHello(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::protocol::hello::v1::HelloResp* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void sayHello(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::protocol::hello::v1::HelloResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::protocol::hello::v1::HelloResp>* AsyncsayHelloRaw(::grpc::ClientContext* context, const ::protocol::hello::v1::HelloReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::protocol::hello::v1::HelloResp>* PrepareAsyncsayHelloRaw(::grpc::ClientContext* context, const ::protocol::hello::v1::HelloReq& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_sayHello_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status sayHello(::grpc::ServerContext* context, const ::protocol::hello::v1::HelloReq* request, ::protocol::hello::v1::HelloResp* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_sayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_sayHello() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_sayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sayHello(::grpc::ServerContext* /*context*/, const ::protocol::hello::v1::HelloReq* /*request*/, ::protocol::hello::v1::HelloResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsayHello(::grpc::ServerContext* context, ::protocol::hello::v1::HelloReq* request, ::grpc::ServerAsyncResponseWriter< ::protocol::hello::v1::HelloResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_sayHello<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_sayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_sayHello() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::protocol::hello::v1::HelloReq, ::protocol::hello::v1::HelloResp>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::protocol::hello::v1::HelloReq* request, ::protocol::hello::v1::HelloResp* response) { return this->sayHello(context, request, response); }));}
    void SetMessageAllocatorFor_sayHello(
        ::grpc::experimental::MessageAllocator< ::protocol::hello::v1::HelloReq, ::protocol::hello::v1::HelloResp>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::protocol::hello::v1::HelloReq, ::protocol::hello::v1::HelloResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_sayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sayHello(::grpc::ServerContext* /*context*/, const ::protocol::hello::v1::HelloReq* /*request*/, ::protocol::hello::v1::HelloResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* sayHello(
      ::grpc::CallbackServerContext* /*context*/, const ::protocol::hello::v1::HelloReq* /*request*/, ::protocol::hello::v1::HelloResp* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* sayHello(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::protocol::hello::v1::HelloReq* /*request*/, ::protocol::hello::v1::HelloResp* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_sayHello<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_sayHello<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_sayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_sayHello() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_sayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sayHello(::grpc::ServerContext* /*context*/, const ::protocol::hello::v1::HelloReq* /*request*/, ::protocol::hello::v1::HelloResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_sayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_sayHello() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_sayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sayHello(::grpc::ServerContext* /*context*/, const ::protocol::hello::v1::HelloReq* /*request*/, ::protocol::hello::v1::HelloResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsayHello(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_sayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_sayHello() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->sayHello(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_sayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sayHello(::grpc::ServerContext* /*context*/, const ::protocol::hello::v1::HelloReq* /*request*/, ::protocol::hello::v1::HelloResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* sayHello(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* sayHello(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_sayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_sayHello() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::protocol::hello::v1::HelloReq, ::protocol::hello::v1::HelloResp>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::protocol::hello::v1::HelloReq, ::protocol::hello::v1::HelloResp>* streamer) {
                       return this->StreamedsayHello(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_sayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status sayHello(::grpc::ServerContext* /*context*/, const ::protocol::hello::v1::HelloReq* /*request*/, ::protocol::hello::v1::HelloResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedsayHello(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::protocol::hello::v1::HelloReq,::protocol::hello::v1::HelloResp>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_sayHello<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_sayHello<Service > StreamedService;
};

}  // namespace v1
}  // namespace hello
}  // namespace protocol


#endif  // GRPC_hello_2eproto__INCLUDED
